"""Word Ladder: pure game rules (no Redis, no I/O beyond the word lists).

Transform ``start_word`` into ``end_word`` one letter-edit at a time. Unlike Wordle/Hangman,
nothing is secret: both endpoints are shown to players from the start, since the puzzle is
*how to connect them*, not a hidden answer to guess.

Unlike Wordle/Hangman's single shared board, **each player races on their own independent
board** -- nobody's edits affect anyone else's, "cooperation" here is limited to optionally
seeing each other's progress (the generic screen-sharing feature; see ``games/state.py``'s
``sharers``/``allow_sharing``, which this module knows nothing about -- the frontend gates what
it shows). The moment any player reaches ``end_word``, the whole game ends and *their* board
becomes the one frozen, canonical result everyone sees from then on. State shape::

    {"start_word": "cold", "end_word": "warm",
     "word_length": 4, "edit_mode": "substitute", "difficulty": "medium",
     "par_steps": 3, "max_rows": 13, "status": "playing",
     "boards": {"p1": {"entries": ["cold", "cord", "card", "ward"]}},
     "winner_pid": None}

A player's board is created lazily on their first action (so players who never touch a row don't
need an entry at all). ``entries`` is that player's own list of rows, index 0 always equal to
``start_word`` (fixed). Any other row may be overwritten in place (``set_word``) — editing row K
never truncates rows after it, because validity (real word? one valid edit from the row above?)
is *computed fresh from raw text* in ``snapshot``, never persisted. A row can therefore sit there
flagged invalid until the player fixes it. The puzzle is solved for everyone the moment any row
in *a* player's board equals ``end_word`` with a valid edit from the row above, regardless of
``par_steps`` — solving in fewer moves than the generated puzzle "just happens" rather than
needing special-case code.

``edit_mode`` is ``"substitute"`` (every rung is the same length) or ``"insert_delete"`` (a step
may also insert/delete one letter, so intermediate rungs can be shorter/longer — though
``start_word``/``end_word`` are always exactly ``word_length`` letters).

Puzzles are generated by rejection sampling (see ``generate_puzzle``): random start word, random
walk of edit-edges, retried until a walk satisfies every constraint, written up in
``scripts/compute_word_ladder_graph.py``. The finished walk is then run through
``_remove_shortcuts``, which uses the same neighbor graph in reverse to find any pair of words in
the path with a common neighbor -- a 2-edge detour shorter than the route the walk actually took
-- and collapses it, so a puzzle never asks a player to take the long way round by accident.
``par_steps`` is derived from the path *after* this collapsing, so it always matches the shortest
real solution.
"""

from __future__ import annotations

import random

from .. import wordlists

KEY = "wordladder"
LABEL = "Word Ladder"

VALID_LENGTHS = frozenset(range(3, 9))  # 3-8 (graph data covers 3-9, the +1 for indel neighbors)
DEFAULT_LENGTH = 5
MIN_STEPS, MAX_STEPS = 2, 10
DEFAULT_STEPS = 5
TIER_ORDER = ("easy", "medium", "hard", "nightmare")
DEFAULT_DIFFICULTY = "medium"
EDIT_MODES = ("substitute", "insert_delete")
DEFAULT_EDIT_MODE = "substitute"
GENERATION_ATTEMPTS = 2000

PLAYING, WON = "playing", "won"


def _clean_length(value) -> int:
    try:
        length = int(value)
    except (TypeError, ValueError):
        return DEFAULT_LENGTH
    return length if length in VALID_LENGTHS else DEFAULT_LENGTH


def _clean_steps(value) -> int:
    try:
        steps = int(value)
    except (TypeError, ValueError):
        return DEFAULT_STEPS
    return steps if MIN_STEPS <= steps <= MAX_STEPS else DEFAULT_STEPS


def _clean_difficulty(value) -> str:
    d = str(value or "").strip().lower()
    return d if d in TIER_ORDER else DEFAULT_DIFFICULTY


def _clean_edit_mode(value) -> str:
    m = str(value or "").strip().lower()
    return m if m in EDIT_MODES else DEFAULT_EDIT_MODE


def _is_valid_edit(prev: str, word: str, edit_mode: str) -> bool:
    """True if ``word`` is exactly one substitution away from ``prev``, or (when
    ``edit_mode == "insert_delete"``) one insertion/deletion away."""
    if prev == word:
        return False
    if len(prev) == len(word):
        return sum(a != b for a, b in zip(prev, word, strict=True)) == 1
    if edit_mode != "insert_delete" or abs(len(prev) - len(word)) != 1:
        return False
    shorter, longer = (prev, word) if len(prev) < len(word) else (word, prev)
    return any(longer[:i] + longer[i + 1 :] == shorter for i in range(len(longer)))


def _tier_index(word: str) -> int:
    tier = wordlists.ladder_tier_of(len(word)).get(word)
    return TIER_ORDER.index(tier) if tier in TIER_ORDER else len(TIER_ORDER) - 1


def _pool(length: int, ceiling_idx: int) -> frozenset[str]:
    tiers = TIER_ORDER[: ceiling_idx + 1]
    return frozenset().union(*(wordlists.ladder_words(length, t) for t in tiers))


def _shared_neighbor(
    word_a: str, word_b: str, ceiling_idx: int, edit_mode: str, word_length: int, exclude: set[str]
) -> str | None:
    """A word reachable from both ``word_a`` and ``word_b`` in one edit (i.e. a length-2 shortcut
    between them), or None if none qualifies. Skips anything already used elsewhere in the
    puzzle (``exclude``), too obscure for the requested difficulty, or -- in ``substitute``
    mode -- the wrong length (an indel rung would make it unreachable by a substitution edit)."""
    neighbors_a = wordlists.ladder_neighbors(len(word_a)).get(word_a, ())
    neighbors_b = set(wordlists.ladder_neighbors(len(word_b)).get(word_b, ()))
    for w in neighbors_a:
        if (
            w in neighbors_b
            and w not in exclude
            and _tier_index(w) <= ceiling_idx
            and (edit_mode == "insert_delete" or len(w) == word_length)
        ):
            return w
    return None


def _remove_shortcuts(
    path: list[str], edit_mode: str, word_length: int, ceiling_idx: int
) -> list[str]:
    """Collapse any detour in ``path`` that a reverse-neighbor lookup shows has a direct 2-edge
    shortcut shorter than the route actually taken, repeatedly, until none remain."""
    path = list(path)
    again = True
    while again:
        again = False
        for i in range(len(path)):
            for j in range(len(path) - 1, i + 2, -1):  # j - i > 2: shortcut of 2 would be shorter
                exclude = set(path) - {path[i], path[j]}
                w = _shared_neighbor(path[i], path[j], ceiling_idx, edit_mode, word_length, exclude)
                if w is not None:
                    path[i + 1 : j] = [w]
                    again = True
                    break
            if again:
                break
    return path


def _has_indel_step(path: list[str]) -> bool:
    return any(len(path[i]) != len(path[i + 1]) for i in range(len(path) - 1))


def generate_puzzle(word_length: int, steps: int, difficulty: str, edit_mode: str) -> list[str]:
    """Rejection-sample a puzzle: random start word, random walk of ``steps`` edit-edges, retried
    until the walk never repeats a word, ends back at ``word_length`` letters, and the most
    obscure word touched is exactly the requested ``difficulty`` tier (not just easier).

    ``# ponytail: bounded rejection sampling with a best-effort fallback below -- a puzzle isn't
    guaranteed to exist for every length/step/difficulty/edit-mode combination (e.g. there are
    very few common 8-letter words); revisit if puzzles routinely fall short of the requested
    step count in practice.``
    """
    ceiling_idx = TIER_ORDER.index(difficulty)
    start_pool = tuple(_pool(word_length, ceiling_idx))
    if not start_pool:
        start_pool = tuple(wordlists.ladder_words(word_length))
    if not start_pool:
        return [""]  # no words of this length at all -- shouldn't happen for 3-8

    best: list[str] | None = None

    for _ in range(GENERATION_ATTEMPTS):
        path = [random.choice(start_pool)]
        visited = {path[0]}
        stuck = False
        for _step in range(steps):
            current = path[-1]
            neighbors = wordlists.ladder_neighbors(len(current)).get(current, ())
            candidates = [
                n
                for n in neighbors
                if n not in visited
                and (edit_mode == "insert_delete" or len(n) == word_length)
                and _tier_index(n) <= ceiling_idx
            ]
            if not candidates:
                stuck = True
                break
            nxt = random.choice(candidates)
            path.append(nxt)
            visited.add(nxt)

        if len(path[-1]) != word_length:
            continue  # only a hard requirement violation -- never usable, even as a fallback
        if not stuck and len(path) == steps + 1:
            if max(_tier_index(w) for w in path) == ceiling_idx:
                collapsed = _remove_shortcuts(path, edit_mode, word_length, ceiling_idx)
                # Collapsing can shorten the walk below the requested step count (a detour turned
                # out to have a shortcut) -- that no longer satisfies the request, so reject and
                # keep sampling rather than handing back a too-short puzzle.
                if len(collapsed) == steps + 1 and (
                    edit_mode != "insert_delete" or _has_indel_step(collapsed)
                ):
                    return collapsed  # full success
        if best is None or len(path) > len(best):
            best = path

    if best is None:
        return [start_pool[0]]
    collapsed_best = _remove_shortcuts(best, edit_mode, word_length, ceiling_idx)
    return collapsed_best if len(collapsed_best) == len(best) else best


def validate_options(options: dict) -> str | None:
    """Check the create-game options. Returns an error message, or None if they're fine.

    Structural checks only -- generation itself (which can be comparatively expensive, see
    ``generate_puzzle``) happens in ``create_state`` and never fails outright.
    """
    opts = options or {}
    try:
        word_length = int(opts.get("wordLength", DEFAULT_LENGTH))
    except (TypeError, ValueError):
        return "wordLength must be a number."
    if word_length not in VALID_LENGTHS:
        return f"Word length must be one of {sorted(VALID_LENGTHS)}."

    try:
        steps = int(opts.get("steps", DEFAULT_STEPS))
    except (TypeError, ValueError):
        return "steps must be a number."
    if not (MIN_STEPS <= steps <= MAX_STEPS):
        return f"Steps must be between {MIN_STEPS} and {MAX_STEPS}."

    difficulty = str(opts.get("difficulty") or "").strip().lower()
    if difficulty and difficulty not in TIER_ORDER:
        return f"Difficulty must be one of {TIER_ORDER}."

    edit_mode = str(opts.get("editMode") or "").strip().lower()
    if edit_mode and edit_mode not in EDIT_MODES:
        return f"Edit mode must be one of {EDIT_MODES}."
    return None


def create_state(options: dict | None = None) -> dict:
    opts = options or {}
    word_length = _clean_length(opts.get("wordLength"))
    steps = _clean_steps(opts.get("steps"))
    difficulty = _clean_difficulty(opts.get("difficulty"))
    edit_mode = _clean_edit_mode(opts.get("editMode"))

    path = generate_puzzle(word_length, steps, difficulty, edit_mode)
    par_steps = len(path) - 1
    return {
        "start_word": path[0],
        "end_word": path[-1],
        "word_length": word_length,
        "edit_mode": edit_mode,
        "difficulty": difficulty,
        "par_steps": par_steps,
        "max_rows": par_steps + 10,
        "boards": {},
        "winner_pid": None,
        "status": PLAYING,
    }


def is_finished(state: dict) -> bool:
    return state.get("status") == WON


def handle_action(state: dict, pid: str, name: str, action: str, data: dict):
    """Apply a player's action. Returns ``(new_state, events)``.

    The only action is ``set_word`` with ``data = {"index": int, "word": str}``, always applied
    to *the acting player's own board* (see module docstring) -- it never touches anyone else's.
    Any row may be set directly -- a player isn't required to fill rows in order, so setting an
    index past their board's current end pads the gap with blank rows (trimmed back off the end
    once they're empty again). Unlike Wordle/Hangman, a word that isn't real or isn't a valid
    edit is **not** rejected -- it's stored as-is and flagged invalid in ``snapshot``, so the only
    protocol-level ``invalid`` reasons are structural: the game is already finished, or the index
    is outside ``1..max_rows-1`` (row 0 is the fixed start word, never editable).
    """
    if is_finished(state):
        return state, [{"kind": "invalid", "reason": "finished"}]
    if action != "set_word":
        return state, [{"kind": "invalid", "reason": "unknown_action"}]

    index = data.get("index")
    if (
        not isinstance(index, int)
        or isinstance(index, bool)
        or not (1 <= index <= state["max_rows"] - 1)
    ):
        return state, [{"kind": "invalid", "reason": "bad_index"}]

    # No .strip(): a word with gaps (leading, internal, or trailing -- unfilled boxes sent as
    # spaces by the client) must stay exactly as typed, not have its letters shifted together into
    # something shorter that then reads as a complete, valid word.
    word = str(data.get("word") or "").lower()[:24]

    entries = state["boards"].get(pid, {}).get("entries") or [state["start_word"]]
    new_entries = list(entries)
    if index >= len(new_entries):
        new_entries.extend([""] * (index + 1 - len(new_entries)))
    new_entries[index] = word
    while len(new_entries) > 1 and new_entries[-1] == "":
        new_entries.pop()

    status = state["status"]
    winner_pid = state["winner_pid"]
    edit_mode = state["edit_mode"]
    end_word = state["end_word"]
    for i in range(1, len(new_entries)):
        if new_entries[i] == end_word and _chain_complete(new_entries[: i + 1], edit_mode):
            new_entries = new_entries[: i + 1]
            status = WON
            winner_pid = pid
            break
    else:
        # The UI never lets a player type into the final (end-word) row -- it's shown only as a
        # locked ghost hint -- so the moment their last real row is one valid edit from end_word,
        # end_word is the only possible next move. Auto-append it rather than leaving the puzzle
        # stuck "in progress" with no way to take that forced last step.
        last = new_entries[-1]
        if (
            last != end_word
            and _is_valid_edit(last, end_word, edit_mode)
            and _chain_complete(new_entries, edit_mode)
        ):
            new_entries.append(end_word)
            status = WON
            winner_pid = pid

    new_boards = {**state["boards"], pid: {"entries": new_entries}}
    new_state = {**state, "boards": new_boards, "status": status, "winner_pid": winner_pid}
    events = [{"kind": "ladder_step", "name": name, "index": index, "word": word}]
    if status == WON:
        events.append({"kind": "win", "name": name, "word": end_word})
    return new_state, events


def _chain_complete(entries: list[str], edit_mode: str) -> bool:
    """True if every row from 1 onward is a real word and a valid edit from the row above it --
    i.e. the whole ladder up to this point holds together, not just the last step into it."""
    return all(
        word in wordlists.ladder_words(len(word))
        and _is_valid_edit(entries[i - 1], word, edit_mode)
        for i, word in enumerate(entries[1:], start=1)
    )


def _row_view(entries: list[str], edit_mode: str) -> list[dict]:
    return [
        {
            "word": word,
            "isWord": bool(word) and word in wordlists.ladder_words(len(word)),
            "isValidEdit": i == 0 or _is_valid_edit(entries[i - 1], word, edit_mode),
        }
        for i, word in enumerate(entries)
    ]


def snapshot(state: dict) -> dict:
    edit_mode = state["edit_mode"]
    winner_pid = state["winner_pid"]
    if state["status"] == WON and winner_pid is not None:
        # Frozen: only the winner's board is shown, to everyone, regardless of sharing.
        boards = {winner_pid: state["boards"][winner_pid]["entries"]}
    else:
        boards = {pid: b["entries"] for pid, b in state["boards"].items()}
    return {
        "startWord": state["start_word"],
        "endWord": state["end_word"],
        "wordLength": state["word_length"],
        "editMode": edit_mode,
        "difficulty": state["difficulty"],
        "parSteps": state["par_steps"],
        "status": state["status"],
        "winnerPid": winner_pid,
        "boards": {pid: _row_view(entries, edit_mode) for pid, entries in boards.items()},
    }


def result(state: dict) -> dict:
    winner_pid = state["winner_pid"]
    entries = (
        state["boards"][winner_pid]["entries"] if winner_pid is not None else [state["start_word"]]
    )
    return {
        "won": state["status"] == WON,
        "answer": state["end_word"],
        "guesses_used": len(entries) - 1,
    }
