"""Word Ladder: pure game rules (no Redis, no I/O beyond the word lists).

Transform ``start_word`` into ``end_word`` one letter-edit at a time. Unlike Wordle/Hangman,
nothing is secret: both endpoints are shown to players from the start, since the puzzle is
*how to connect them*, not a hidden answer to guess.

Unlike Wordle/Hangman's single shared board, **each player races on their own independent
board** -- nobody's edits affect anyone else's, "cooperation" here is limited to optionally
seeing each other's progress (the generic screen-sharing feature; see ``games/state.py``'s
``sharers``/``allow_sharing``, which this module knows nothing about -- the frontend gates what
it shows). The moment any player reaches ``end_word``, the whole game ends and *their* board
becomes the one frozen, canonical result everyone sees from then on. State shape::

    {"start_word": "cold", "end_word": "warm",
     "word_length": 4, "edit_mode": "substitute", "difficulty": "medium",
     "par_steps": 3, "max_rows": 13, "status": "playing",
     "boards": {"p1": {"entries": ["cold", "cord", "card", "ward"]}},
     "winner_pid": None, "solution": ["cold", "cord", "card", "warm"],
     "solution_revealed": False}

A player's board is created lazily on their first action (so players who never touch a row don't
need an entry at all). ``entries`` is that player's own list of rows, index 0 always equal to
``start_word`` (fixed). Any other row may be overwritten in place (``set_word``) — editing row K
never truncates rows after it, because validity (real word? one valid edit from the row above?)
is *computed fresh from raw text* in ``snapshot``, never persisted. A row can therefore sit there
flagged invalid until the player fixes it. The puzzle is solved for everyone the moment any row
in *a* player's board equals ``end_word`` with a valid edit from the row above, regardless of
``par_steps`` — solving in fewer moves than the generated puzzle "just happens" rather than
needing special-case code.

``edit_mode`` is ``"substitute"`` (every rung is the same length) or ``"insert_delete"`` (a step
may also insert/delete one letter, so intermediate rungs can be shorter/longer — though
``start_word``/``end_word`` are always exactly ``word_length`` letters).

Puzzles are generated by rejection sampling (see ``generate_puzzle``): random start word, random
walk of edit-edges to a candidate end word, then a real BFS shortest-path solve
(``_bfs_shortest_path``) between the two over the same neighbor graph (built offline by
``scripts/compute_word_ladder_graph.py``). If the solved route is shorter than the requested step
count, the walk is extended further from the end word and re-solved, repeating until the solved
length matches -- so a puzzle never asks a player to take the long way round by accident, and
``par_steps`` always matches the true shortest solution by construction.
"""

from __future__ import annotations

import random
from collections import deque

from .. import wordlists

KEY = "wordladder"
LABEL = "Word Ladder"

VALID_LENGTHS = frozenset(range(3, 9))  # 3-8 (graph data covers 3-9, the +1 for indel neighbors)
DEFAULT_LENGTH = 5
MIN_STEPS, MAX_STEPS = 2, 10
DEFAULT_STEPS = 5
TIER_ORDER = ("easy", "medium", "hard", "nightmare")
DEFAULT_DIFFICULTY = "medium"
EDIT_MODES = ("substitute", "insert_delete")
DEFAULT_EDIT_MODE = "substitute"
GENERATION_ATTEMPTS = 2000

PLAYING, WON = "playing", "won"


def _clean_length(value) -> int:
    try:
        length = int(value)
    except (TypeError, ValueError):
        return DEFAULT_LENGTH
    return length if length in VALID_LENGTHS else DEFAULT_LENGTH


def _clean_steps(value) -> int:
    try:
        steps = int(value)
    except (TypeError, ValueError):
        return DEFAULT_STEPS
    return steps if MIN_STEPS <= steps <= MAX_STEPS else DEFAULT_STEPS


def _clean_difficulty(value) -> str:
    d = str(value or "").strip().lower()
    return d if d in TIER_ORDER else DEFAULT_DIFFICULTY


def _clean_edit_mode(value) -> str:
    m = str(value or "").strip().lower()
    return m if m in EDIT_MODES else DEFAULT_EDIT_MODE


def _is_valid_edit(prev: str, word: str, edit_mode: str) -> bool:
    """True if ``word`` is exactly one substitution away from ``prev``, or (when
    ``edit_mode == "insert_delete"``) one insertion/deletion away."""
    if prev == word:
        return False
    if len(prev) == len(word):
        return sum(a != b for a, b in zip(prev, word, strict=True)) == 1
    if edit_mode != "insert_delete" or abs(len(prev) - len(word)) != 1:
        return False
    shorter, longer = (prev, word) if len(prev) < len(word) else (word, prev)
    return any(longer[:i] + longer[i + 1 :] == shorter for i in range(len(longer)))


def _tier_index(word: str) -> int:
    tier = wordlists.ladder_tier_of(len(word)).get(word)
    return TIER_ORDER.index(tier) if tier in TIER_ORDER else len(TIER_ORDER) - 1


def _pool(length: int, ceiling_idx: int) -> frozenset[str]:
    tiers = TIER_ORDER[: ceiling_idx + 1]
    return frozenset().union(*(wordlists.ladder_words(length, t) for t in tiers))


def _allowed_neighbors(word: str, edit_mode: str, word_length: int, ceiling_idx: int) -> list[str]:
    """Neighbors of ``word`` that qualify for this puzzle: within the difficulty ceiling, and --
    in ``substitute`` mode -- the same length (an indel rung would be unreachable by a
    substitution edit)."""
    neighbors = wordlists.ladder_neighbors(len(word)).get(word, ())
    return [
        n
        for n in neighbors
        if _tier_index(n) <= ceiling_idx and (edit_mode == "insert_delete" or len(n) == word_length)
    ]


def _bfs_shortest_path(
    start: str, end: str, edit_mode: str, word_length: int, ceiling_idx: int
) -> list[str] | None:
    """The true shortest path from ``start`` to ``end`` over the allowed neighbor graph, or None
    if they're not connected within it."""
    if start == end:
        return [start]
    came_from: dict[str, str] = {}
    queue = deque([start])
    while queue:
        word = queue.popleft()
        for n in _allowed_neighbors(word, edit_mode, word_length, ceiling_idx):
            if n in came_from or n == start:
                continue
            came_from[n] = word
            if n == end:
                path = [n]
                while path[-1] != start:
                    path.append(came_from[path[-1]])
                path.reverse()
                return path
            queue.append(n)
    return None


def _has_indel_step(path: list[str]) -> bool:
    return any(len(path[i]) != len(path[i + 1]) for i in range(len(path) - 1))


MAX_EXTEND_ROUNDS = 20


def _walk_to_length(
    path: list[str],
    visited: set[str],
    target: int,
    edit_mode: str,
    word_length: int,
    ceiling_idx: int,
) -> bool:
    """Extend ``path`` in place (random walk) until it has ``target`` edges. Returns False if it
    gets stuck (no unvisited qualifying neighbor) before reaching that length."""
    while len(path) - 1 < target:
        candidates = [
            n
            for n in _allowed_neighbors(path[-1], edit_mode, word_length, ceiling_idx)
            if n not in visited
        ]
        if not candidates:
            return False
        nxt = random.choice(candidates)
        path.append(nxt)
        visited.add(nxt)
    return True


def generate_puzzle(word_length: int, steps: int, difficulty: str, edit_mode: str) -> list[str]:
    """Rejection-sample a puzzle: random start word, random walk to a candidate end word, then
    BFS-solve the true shortest path between them (``_bfs_shortest_path``). If that solve is
    shorter than the requested ``steps``, the walk is extended further from the end word and
    re-solved, repeating until the solved length matches.

    ``# ponytail: bounded rejection sampling with a best-effort fallback below -- a puzzle isn't
    guaranteed to exist for every length/step/difficulty/edit-mode combination (e.g. there are
    very few common 8-letter words); revisit if puzzles routinely fall short of the requested
    step count in practice.``
    """
    ceiling_idx = TIER_ORDER.index(difficulty)
    start_pool = tuple(_pool(word_length, ceiling_idx))
    if not start_pool:
        start_pool = tuple(wordlists.ladder_words(word_length))
    if not start_pool:
        return [""]  # no words of this length at all -- shouldn't happen for 3-8

    best: list[str] | None = None

    for _ in range(GENERATION_ATTEMPTS):
        start = random.choice(start_pool)
        path = [start]
        visited = {start}
        target = steps

        for _ in range(MAX_EXTEND_ROUNDS):
            stuck = not _walk_to_length(path, visited, target, edit_mode, word_length, ceiling_idx)
            end = path[-1]
            if len(end) != word_length:
                break  # bad endpoint -- never usable, try a fresh start

            solved = _bfs_shortest_path(start, end, edit_mode, word_length, ceiling_idx)
            if solved is None:
                break  # shouldn't happen (a walk connects them), but be safe
            solved_steps = len(solved) - 1

            if best is None or solved_steps > len(best) - 1:
                best = solved
            if solved_steps == steps:
                if max(_tier_index(w) for w in solved) == ceiling_idx and (
                    edit_mode != "insert_delete" or _has_indel_step(solved)
                ):
                    return solved  # full success
                break  # right length but misses difficulty/indel -- try a fresh start
            if stuck or solved_steps > steps:
                break  # can't reach the target from here -- try a fresh start
            target += steps - solved_steps  # walk further to outrun the shortcut

    if best is None:
        return [start_pool[0]]
    return best


def validate_options(options: dict) -> str | None:
    """Check the create-game options. Returns an error message, or None if they're fine.

    Structural checks only -- generation itself (which can be comparatively expensive, see
    ``generate_puzzle``) happens in ``create_state`` and never fails outright.
    """
    opts = options or {}
    try:
        word_length = int(opts.get("wordLength", DEFAULT_LENGTH))
    except (TypeError, ValueError):
        return "wordLength must be a number."
    if word_length not in VALID_LENGTHS:
        return f"Word length must be one of {sorted(VALID_LENGTHS)}."

    try:
        steps = int(opts.get("steps", DEFAULT_STEPS))
    except (TypeError, ValueError):
        return "steps must be a number."
    if not (MIN_STEPS <= steps <= MAX_STEPS):
        return f"Steps must be between {MIN_STEPS} and {MAX_STEPS}."

    difficulty = str(opts.get("difficulty") or "").strip().lower()
    if difficulty and difficulty not in TIER_ORDER:
        return f"Difficulty must be one of {TIER_ORDER}."

    edit_mode = str(opts.get("editMode") or "").strip().lower()
    if edit_mode and edit_mode not in EDIT_MODES:
        return f"Edit mode must be one of {EDIT_MODES}."
    return None


def create_state(options: dict | None = None) -> dict:
    opts = options or {}
    word_length = _clean_length(opts.get("wordLength"))
    steps = _clean_steps(opts.get("steps"))
    difficulty = _clean_difficulty(opts.get("difficulty"))
    edit_mode = _clean_edit_mode(opts.get("editMode"))

    path = generate_puzzle(word_length, steps, difficulty, edit_mode)
    par_steps = len(path) - 1
    return {
        "start_word": path[0],
        "end_word": path[-1],
        "word_length": word_length,
        "edit_mode": edit_mode,
        "difficulty": difficulty,
        "par_steps": par_steps,
        "max_rows": par_steps + 10,
        "boards": {},
        "winner_pid": None,
        "status": PLAYING,
        "solution": path,
        "solution_revealed": False,
    }


def is_finished(state: dict) -> bool:
    return state.get("status") == WON


def handle_action(state: dict, pid: str, name: str, action: str, data: dict):
    """Apply a player's action. Returns ``(new_state, events)``.

    ``reveal_solution`` (no data) flips a one-way flag exposing the generator's BFS-solved path
    (see ``generate_puzzle``) to everyone via ``snapshot``; it's always allowed, even after the
    game is won, since peeking at the route doesn't affect anyone's board.

    Otherwise the only action is ``set_word`` with ``data = {"index": int, "word": str}``, always
    applied to *the acting player's own board* (see module docstring) -- it never touches anyone
    else's. Any row may be set directly -- a player isn't required to fill rows in order, so setting
    an index past their board's current end pads the gap with blank rows (trimmed back off the end
    once they're empty again). Unlike Wordle/Hangman, a word that isn't real or isn't a valid
    edit is **not** rejected -- it's stored as-is and flagged invalid in ``snapshot``, so the only
    protocol-level ``invalid`` reasons are structural: the game is already finished, or the index
    is outside ``1..max_rows-1`` (row 0 is the fixed start word, never editable).
    """
    if action == "reveal_solution":
        new_state = {**state, "solution_revealed": True}
        return new_state, [{"kind": "solution_revealed", "name": name}]
    if is_finished(state):
        return state, [{"kind": "invalid", "reason": "finished"}]
    if action != "set_word":
        return state, [{"kind": "invalid", "reason": "unknown_action"}]

    index = data.get("index")
    if (
        not isinstance(index, int)
        or isinstance(index, bool)
        or not (1 <= index <= state["max_rows"] - 1)
    ):
        return state, [{"kind": "invalid", "reason": "bad_index"}]

    # No .strip(): a word with gaps (leading, internal, or trailing -- unfilled boxes sent as
    # spaces by the client) must stay exactly as typed, not have its letters shifted together into
    # something shorter that then reads as a complete, valid word.
    word = str(data.get("word") or "").lower()[:24]

    entries = state["boards"].get(pid, {}).get("entries") or [state["start_word"]]
    new_entries = list(entries)
    if index >= len(new_entries):
        new_entries.extend([""] * (index + 1 - len(new_entries)))
    new_entries[index] = word
    while len(new_entries) > 1 and new_entries[-1] == "":
        new_entries.pop()

    status = state["status"]
    winner_pid = state["winner_pid"]
    edit_mode = state["edit_mode"]
    end_word = state["end_word"]
    for i in range(1, len(new_entries)):
        if new_entries[i] == end_word and _chain_complete(new_entries[: i + 1], edit_mode):
            new_entries = new_entries[: i + 1]
            status = WON
            winner_pid = pid
            break
    else:
        # The UI never lets a player type into the final (end-word) row -- it's shown only as a
        # locked ghost hint -- so the moment their last real row is one valid edit from end_word,
        # end_word is the only possible next move. Auto-append it rather than leaving the puzzle
        # stuck "in progress" with no way to take that forced last step.
        last = new_entries[-1]
        if (
            last != end_word
            and _is_valid_edit(last, end_word, edit_mode)
            and _chain_complete(new_entries, edit_mode)
        ):
            new_entries.append(end_word)
            status = WON
            winner_pid = pid

    new_boards = {**state["boards"], pid: {"entries": new_entries}}
    new_state = {**state, "boards": new_boards, "status": status, "winner_pid": winner_pid}
    events = [{"kind": "ladder_step", "name": name, "index": index, "word": word}]
    if status == WON:
        events.append({"kind": "win", "name": name, "word": end_word})
    return new_state, events


def _chain_complete(entries: list[str], edit_mode: str) -> bool:
    """True if every row from 1 onward is a real word and a valid edit from the row above it --
    i.e. the whole ladder up to this point holds together, not just the last step into it."""
    return all(
        word in wordlists.ladder_words(len(word))
        and _is_valid_edit(entries[i - 1], word, edit_mode)
        for i, word in enumerate(entries[1:], start=1)
    )


def _row_view(entries: list[str], edit_mode: str) -> list[dict]:
    return [
        {
            "word": word,
            "isWord": bool(word) and word in wordlists.ladder_words(len(word)),
            "isValidEdit": i == 0 or _is_valid_edit(entries[i - 1], word, edit_mode),
        }
        for i, word in enumerate(entries)
    ]


def snapshot(state: dict) -> dict:
    edit_mode = state["edit_mode"]
    winner_pid = state["winner_pid"]
    if state["status"] == WON and winner_pid is not None:
        # Frozen: only the winner's board is shown, to everyone, regardless of sharing.
        boards = {winner_pid: state["boards"][winner_pid]["entries"]}
    else:
        boards = {pid: b["entries"] for pid, b in state["boards"].items()}
    return {
        "startWord": state["start_word"],
        "endWord": state["end_word"],
        "wordLength": state["word_length"],
        "editMode": edit_mode,
        "difficulty": state["difficulty"],
        "parSteps": state["par_steps"],
        "status": state["status"],
        "winnerPid": winner_pid,
        "boards": {pid: _row_view(entries, edit_mode) for pid, entries in boards.items()},
        "solution": state["solution"] if state["solution_revealed"] else None,
    }


def result(state: dict) -> dict:
    winner_pid = state["winner_pid"]
    entries = (
        state["boards"][winner_pid]["entries"] if winner_pid is not None else [state["start_word"]]
    )
    return {
        "won": state["status"] == WON,
        "answer": state["end_word"],
        "guesses_used": len(entries) - 1,
    }
