# Generated by Django 6.0.6 on 2026-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinishedGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_type", models.CharField(default="wordle", max_length=32)),
                ("answer", models.CharField(blank=True, max_length=32)),
                ("won", models.BooleanField(default=False)),
                ("guesses_used", models.PositiveSmallIntegerField(default=0)),
                ("player_names", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
